### ISSUE TITLE
在create-vite创建的react项目使用了plugin-react插件时无法显示代码块demo或外部demo

### ISSUE THREAD

**Issue by justoneone** [Codpoe/pressify#1]
pressify版本0.1.1

重现步骤：

1. 使用`npm create vite`新建一个`react-ts`模版的项目
2. 安装默认的依赖包，再安装`pressify`
3. 在`package.json`中修改`scripts`

```
{
  "scripts": {
    "dev": "pressify dev",
    "build": "pressify build",
    "serve": "pressify serve"
  }
}
```

4. 根目录创建`.pressify`目录配置`pages: 'src'`指定`src`为文档目录
5. 清空`src`目录，新建`README.md`使用官方提供的代码块demo如下：

```
```ts demo
export default function Foo() {
  return (
    <button
      className="px-3 py-1 rounded text-white bg-c-brand hover:bg-c-brand-light"
      onClick={() => alert('Hi')}
    >
      Hello World
    </button>
  );
}
```

运行项目`npm run dev`发现无法显示代码块demo或外部demo.

补充：在非ts项目中也无法显示代码块demo，报错如下：
```
ERROR: The symbol "prevRefreshReg" has already been declared

ERROR: The symbol "prevRefreshSig" has already been declared
```

**Comment by Codpoe** [comment]
Pressify 已经内置 `@vitejs/plugin-react`，如果项目的 vite.config.ts 里还有 `@vitejs/plugin-react` 的话就存在两个一样的插件了，这会导致文件的重复处理。

目前建议去掉 vite.config.ts 里的 react 插件。后续 Pressify 会考虑增加配置项用于决定是否需要读取项目里的 vite.config.ts 配置，因为在一些场景下，项目本身的 vite 配置和 Pressify 的配置会产生冲突。
