### ISSUE TITLE
使用pressify配合vite3.0时构建报错

### ISSUE THREAD

**Issue by justoneone** [Codpoe/pressify#10]
pressify版本0.1.7

重现步骤：
1. 安装`pressify`，再安装`vite@3.0.0`
2. 运行项目`npm run dev`可以正常显示
3. 构建项目`npm run build`报错如下：

```
 ERROR  build error:
 Missing "./preload-helper" export in "vite" package
```

补充：如果安装`vite@2.x`，构建项目没有报错

建议：`Pressify`能够内置支持最新版本的`vite 3`

**Comment by Codpoe** [comment]
可以升级到 pressify v1 试试，这个版本内置了 vite@3 ⚡️

**Comment by justoneone** [comment]
新版本 v1.0.1 已测试正常 😄
