### ISSUE TITLE
设置vite的base后构建时报错

### ISSUE THREAD

**Issue by justoneone** [Codpoe/pressify#6]
pressify版本0.1.1

重现步骤：

1. 根目录创建.pressify目录配置pages: 'src/zh'指定zh为文档目录，设置vite的base为`/docs/`
```
export default {
    pages: "src/zh",
    vite: {
        base: "/docs/",
    },
};
```
3. 在src目录创建如下文件用来最小化场景的复现：
src
├──zh
├──├─ index.mdx
├──components
├──├─ Demo.tsx
├──└─Test.tsx

`index.mdx`代码如下：
```
## 外部demo

<Demo src="../components/Demo.tsx" />
```

`Demo.tsx`代码如下：
```
import React from "react";
import { Test } from "./Test";

const Demo = () => (
  <>
    <p>测试标题</p>
    <Test />
  </>
);

export default Demo;
```

`Test.tsx`代码如下：
```
import React from "react";

export const Test: React.FC = () => {
  return <div>测试内容</div>;
};
```

3. 运行`npm run dev`可以正常显示外部demo
4. 运行`npm run build`构建时报错
```
ERROR  build error:
Cannot read properties of undefined (reading 'htmlAttributes')
```

补充：如果去掉vite的base设置，构建正常无报错

**Comment by Codpoe** [comment]
可以试下 0.1.4 这个版本。

**Comment by justoneone** [comment]
> 可以试下 0.1.4 这个版本。

新版本已测试正常 😄
